<?php
namespace app\index\controller;

use app\common\controller\HomeBase;
use think\facade\View;
use think\facade\Db;
use app\index\model\Index as IndexModel;

class Index extends HomeBase{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //用户首页
    public function index(){
        $config = Db::name('config')->select()->toArray();
        $config = array_column($config, 'value', 'name');
        $cates = Db::name('cate')->where('status', 1)->select()->toArray();
        view::assign([
            'config' => $config,
            'cates' => $cates
        ]);
        return view();
    }

    //返回配置信息
    public function config(){
        return json(['code' => 1, 'config' => $this->config]);
    }

    //chatgpt聊天函数
    public function chatgpt(){
        if(request()->isPost()) {
            $param = request()->post();

            $context = $param['context'];
            $arr = array_slice($context, -6);// 倒数5个
            $last = $arr[count($arr) - 1]['content'];


            $index = new IndexModel();
            $Keys = $index->getKey();
            $open_ai_key = $Keys['data'];
            if($Keys['code'] != 1) return json(['code' => 0, 'answer' => '后台key不足,请联系管理员']);
            $token = $index->tokencheck();
            $user = $token['userinfo'];
            if($token['code'] != 1) return json(['code' => 0, 'answer' => 'Token错误']);
            $vip = $index->vipcheck($user, $this->config);
            if($vip['code'] != 1) return json(['code' => 0, 'answer' => $vip['msg']]);
            //Db::table('think_user')->where('id',10)->sum('score');

            if(mb_substr($last, 0, 1) == "画") {
                $chat = imges($open_ai_key, $last, $this->config['apidomain']);
                $status = ($chat['code'] == 1) ? 1 : 0;
                //扣次
                if($status == 1 && $this->config['isfree'] != 1) $index->ask($last, 'png', 2, $user['id']);

                if(strpos($chat['text'], "You exceeded your current quota") !== FALSE) {
                    Db::name('key')->where('key', $open_ai_key)->update(['status' => 0, 'endtime' => date('Y-m-d H:i:s')]);
                    return $this->chatgpt();
                }
                return json_encode([
                    "ask" => $last,
                    "answer" => $chat['text'],
                    "code" => $status,
                ]);
            } else {
                $chat = completions($open_ai_key, $arr, $this->config['apidomain']);
                $status = $chat['code'] == 1 ? 1 : 0;
                if($status == 1 & $this->config['isfree'] != 1) $index->ask($last, $chat['text'], 1, $user['id']);
                if(strpos($chat['text'], "You exceeded your current quota") !== FALSE) {
                    Db::name('key')->where('key', $open_ai_key)->update(['status' => 0, 'endtime' => date('Y-m-d H:i:s')]);
                    return $this->chatgpt();
                }
            }
        }
    }
}